/**
 * @section imports:externals
 */

import "dotenv/config";

/**
 * @section imports:internals
 */

// empty

/**
 * @section consts
 */

const env = process.env;

/**
 * @section types
 */

type Config = {
  MODEL_ARTIFACTS_ROOT_PATH: string;
  MODEL_REGISTRY_DIRECTORY_PATH: string;
  MODEL_REGISTRY_FILE_PATH: string;
  TRAINING_WINDOW_REGISTRY_FILE_PATH: string;
  MIN_MARKET_WINDOW_COVERAGE_RATIO: number;
  MODEL_SERVICE_LOOP_DELAY_MS: number;
  MODEL_SERVICE_MAX_CONCURRENT_COMBINATIONS: number;
  MODEL_TRAINING_BATCH_WINDOW_COUNT: number;
  MODEL_BACKTEST_HOLDOUT_WINDOW_COUNT: number;
  MODEL_TRAINING_INTERVAL_MS: number;
  MODEL_BACKTEST_INTERVAL_MS: number;
  MODEL_SCORE_AUC_WEIGHT: number;
  MODEL_SCORE_F1_WEIGHT: number;
  MODEL_SCORE_LOG_LOSS_WEIGHT: number;
  MODEL_SCORE_RECENCY_WEIGHT: number;
  MODEL_SCORE_STABILITY_WEIGHT: number;
  CLICK_COLLECTOR_HOST: string;
  CLICK_COLLECTOR_USERNAME: string;
  CLICK_COLLECTOR_PASSWORD: string;
  VALIDATION_REPORTS_ROOT_PATH: string;
  VALIDATION_DEFAULT_MARKET_LIMIT: number;
  VALIDATION_RANDOM_SAMPLE_COUNT: number;
  VALIDATION_MARKET_TIMEOUT_MS: number;
  MODEL_BACKTEST_RELEVANT_CONFIDENCE_THRESHOLD: number;
};

const CONFIG: Config = {
  MODEL_ARTIFACTS_ROOT_PATH: env.MODEL_ARTIFACTS_ROOT_PATH || "artifacts/models",
  MODEL_REGISTRY_DIRECTORY_PATH: env.MODEL_REGISTRY_DIRECTORY_PATH || "artifacts/registry",
  MODEL_REGISTRY_FILE_PATH: env.MODEL_REGISTRY_FILE_PATH || "artifacts/registry/model-catalog.json",
  TRAINING_WINDOW_REGISTRY_FILE_PATH: env.TRAINING_WINDOW_REGISTRY_FILE_PATH || "artifacts/registry/training-window-registry.json",
  MIN_MARKET_WINDOW_COVERAGE_RATIO: Number(env.MIN_MARKET_WINDOW_COVERAGE_RATIO || 0.8),
  MODEL_SERVICE_LOOP_DELAY_MS: Number(env.MODEL_SERVICE_LOOP_DELAY_MS || 5_000),
  MODEL_SERVICE_MAX_CONCURRENT_COMBINATIONS: Number(env.MODEL_SERVICE_MAX_CONCURRENT_COMBINATIONS || 1),
  MODEL_TRAINING_BATCH_WINDOW_COUNT: Number(env.MODEL_TRAINING_BATCH_WINDOW_COUNT || 10),
  MODEL_BACKTEST_HOLDOUT_WINDOW_COUNT: Number(env.MODEL_BACKTEST_HOLDOUT_WINDOW_COUNT || 10),
  MODEL_TRAINING_INTERVAL_MS: Number(env.MODEL_TRAINING_INTERVAL_MS || 15 * 60 * 1000),
  MODEL_BACKTEST_INTERVAL_MS: Number(env.MODEL_BACKTEST_INTERVAL_MS || 60 * 60 * 1000),
  MODEL_SCORE_AUC_WEIGHT: Number(env.MODEL_SCORE_AUC_WEIGHT || 0.35),
  MODEL_SCORE_F1_WEIGHT: Number(env.MODEL_SCORE_F1_WEIGHT || 0.25),
  MODEL_SCORE_LOG_LOSS_WEIGHT: Number(env.MODEL_SCORE_LOG_LOSS_WEIGHT || 0.2),
  MODEL_SCORE_RECENCY_WEIGHT: Number(env.MODEL_SCORE_RECENCY_WEIGHT || 0.1),
  MODEL_SCORE_STABILITY_WEIGHT: Number(env.MODEL_SCORE_STABILITY_WEIGHT || 0.1),
  CLICK_COLLECTOR_HOST: env.CLICK_COLLECTOR_HOST || "http://192.168.1.2:8123",
  CLICK_COLLECTOR_USERNAME: env.CLICK_COLLECTOR_USERNAME || "default",
  CLICK_COLLECTOR_PASSWORD: env.CLICK_COLLECTOR_PASSWORD || "default",
  VALIDATION_REPORTS_ROOT_PATH: env.VALIDATION_REPORTS_ROOT_PATH || "artifacts/validation",
  VALIDATION_DEFAULT_MARKET_LIMIT: Number(env.VALIDATION_DEFAULT_MARKET_LIMIT || 20),
  VALIDATION_RANDOM_SAMPLE_COUNT: Number(env.VALIDATION_RANDOM_SAMPLE_COUNT || 25),
  VALIDATION_MARKET_TIMEOUT_MS: Number(env.VALIDATION_MARKET_TIMEOUT_MS || 30_000),
  MODEL_BACKTEST_RELEVANT_CONFIDENCE_THRESHOLD: Number(env.MODEL_BACKTEST_RELEVANT_CONFIDENCE_THRESHOLD || 0.65)
};

export default CONFIG;
